name: Update Gists Metadata

on:
  schedule:
    - cron: '0 0 * * *'  # 24h
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch metadata
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_API_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/gists?q=[lestajs]%20in:description" \
            | jq '[.[] | {id, html_url, description, updated_at}]' \
            > gists-metadata.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gists-metadata.json
          git commit -m "Update gist links $(date +'%Y-%m-%d')"
          git push
